From rrojano/jdk8
workdir /app
#exponse 8080
cmd ["app/ejecutar.sh"]
add app/Productos-0.0.1-SNAPSHOT.jar /app/Productos-0.0.1-SNAPSHOT.jar
add ejecutar.sh /app/ejecutar.sh
run chmod 755 /app/ejecutar.sh