From rrojano/jdk8

#exponse 8080
add app/ConsultaPromociones-0.0.1-SNAPSHOT.jar /app/ConsultaPromociones-0.0.1-SNAPSHOT.jar
WORKDIR /app
cmd java -jar -Dserver.port=$PORT ConsultaPromociones-0.0.1-SNAPSHOT.jar
